/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MermaidZoomPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// settings.ts
var import_obsidian2 = require("obsidian");

// i18n.ts
var import_obsidian = require("obsidian");

// locale/en.json
var en_default = {
  "setting.zoomSensitivity.name": "Zoom sensitivity",
  "setting.zoomSensitivity.desc": "How strongly mouse-wheel scrolling and pinch gestures zoom. Lower values feel gentler \u2014 try 0.5x if scrolling on a trackpad or Magic Mouse zooms too fast. Takes effect the next time a diagram is opened fullscreen.",
  "setting.containerBorder.name": "Show container border",
  "setting.containerBorder.desc": "Display a dashed border around each diagram container to help visualize the zoom area boundaries.",
  "setting.alignment.name": "Default alignment",
  "setting.alignment.desc": "Horizontal alignment of the diagram within its container.",
  "setting.alignment.option.left": "Left",
  "setting.alignment.option.center": "Center",
  "setting.alignment.option.right": "Right",
  "settings.note": "Appearance settings (alignment, border) apply to open notes immediately; zoom sensitivity takes effect the next time a diagram is opened fullscreen.",
  "setting.exportDestination.name": "PNG export destination",
  "setting.exportDestination.desc": "Where exported PNG images of diagrams are saved.",
  "setting.exportDestination.option.vault": "Vault (attachments folder)",
  "setting.exportDestination.option.download": "Download to your computer",
  "export.buttonTitle": "Export as PNG",
  "export.savedNotice": "Saved: {path}",
  "export.downloadedNotice": "Downloaded: {name}",
  "export.failedNotice": "Failed to export PNG",
  "modal.close": "Close",
  "modal.zoomIn": "Zoom in",
  "modal.zoomOut": "Zoom out",
  "modal.reset": "Reset zoom"
};

// locale/zh.json
var zh_default = {
  "setting.zoomSensitivity.name": "\u7F29\u653E\u7075\u654F\u5EA6",
  "setting.zoomSensitivity.desc": "\u9F20\u6807\u6EDA\u8F6E\u548C\u53CC\u6307\u634F\u5408\u7684\u7F29\u653E\u5F3A\u5EA6\u3002\u6570\u503C\u8D8A\u5C0F\u624B\u611F\u8D8A\u67D4\u548C\u2014\u2014\u82E5\u89E6\u63A7\u677F\u6216\u5999\u63A7\u9F20\u6807\u6EDA\u52A8\u7F29\u653E\u8FC7\u5FEB\uFF0C\u53EF\u5C1D\u8BD5 0.5x\u3002\u91CD\u65B0\u6253\u5F00\u5168\u5C4F\u89C6\u56FE\u540E\u751F\u6548\u3002",
  "setting.containerBorder.name": "\u663E\u793A\u5BB9\u5668\u8FB9\u6846",
  "setting.containerBorder.desc": "\u5728\u6BCF\u4E2A\u56FE\u8868\u5BB9\u5668\u5468\u56F4\u663E\u793A\u865A\u7EBF\u8FB9\u6846\uFF0C\u4FBF\u4E8E\u770B\u6E05\u7F29\u653E\u533A\u57DF\u7684\u8FB9\u754C\u3002",
  "setting.alignment.name": "\u9ED8\u8BA4\u5BF9\u9F50\u65B9\u5F0F",
  "setting.alignment.desc": "\u56FE\u8868\u5728\u5BB9\u5668\u5185\u7684\u6C34\u5E73\u5BF9\u9F50\u65B9\u5F0F\u3002",
  "setting.alignment.option.left": "\u5DE6\u5BF9\u9F50",
  "setting.alignment.option.center": "\u5C45\u4E2D",
  "setting.alignment.option.right": "\u53F3\u5BF9\u9F50",
  "settings.note": "\u5916\u89C2\u8BBE\u7F6E\uFF08\u5BF9\u9F50\u3001\u8FB9\u6846\uFF09\u7ACB\u5373\u4F5C\u7528\u4E8E\u5DF2\u6253\u5F00\u7684\u7B14\u8BB0\uFF1B\u7F29\u653E\u7075\u654F\u5EA6\u5728\u5168\u5C4F\u89C6\u56FE\u4E0B\u6B21\u6253\u5F00\u65F6\u751F\u6548\u3002",
  "setting.exportDestination.name": "PNG \u5BFC\u51FA\u4F4D\u7F6E",
  "setting.exportDestination.desc": "\u5BFC\u51FA\u7684\u56FE\u8868 PNG \u56FE\u7247\u4FDD\u5B58\u5230\u54EA\u91CC\u3002",
  "setting.exportDestination.option.vault": "\u4ED3\u5E93\uFF08\u9644\u4EF6\u76EE\u5F55\uFF09",
  "setting.exportDestination.option.download": "\u4E0B\u8F7D\u5230\u672C\u5730",
  "export.buttonTitle": "\u5BFC\u51FA\u4E3A PNG",
  "export.savedNotice": "\u5DF2\u4FDD\u5B58\uFF1A{path}",
  "export.downloadedNotice": "\u5DF2\u4E0B\u8F7D\uFF1A{name}",
  "export.failedNotice": "\u5BFC\u51FA PNG \u5931\u8D25",
  "modal.close": "\u5173\u95ED",
  "modal.zoomIn": "\u653E\u5927",
  "modal.zoomOut": "\u7F29\u5C0F",
  "modal.reset": "\u91CD\u7F6E\u7F29\u653E"
};

// locale/zh-TW.json
var zh_TW_default = {
  "setting.zoomSensitivity.name": "\u7E2E\u653E\u9748\u654F\u5EA6",
  "setting.zoomSensitivity.desc": "\u6ED1\u9F20\u6EFE\u8F2A\u8207\u96D9\u6307\u634F\u5408\u7684\u7E2E\u653E\u5F37\u5EA6\u3002\u6578\u503C\u8D8A\u5C0F\u624B\u611F\u8D8A\u67D4\u548C\u2014\u2014\u82E5\u89F8\u63A7\u677F\u6216\u5DE7\u63A7\u6ED1\u9F20\u6372\u52D5\u7E2E\u653E\u904E\u5FEB\uFF0C\u53EF\u5617\u8A66 0.5x\u3002\u91CD\u65B0\u958B\u555F\u5168\u87A2\u5E55\u6AA2\u8996\u5F8C\u751F\u6548\u3002",
  "setting.containerBorder.name": "\u986F\u793A\u5BB9\u5668\u908A\u6846",
  "setting.containerBorder.desc": "\u5728\u6BCF\u500B\u5716\u8868\u5BB9\u5668\u5468\u570D\u986F\u793A\u865B\u7DDA\u908A\u6846\uFF0C\u4FBF\u65BC\u770B\u6E05\u7E2E\u653E\u5340\u57DF\u7684\u908A\u754C\u3002",
  "setting.alignment.name": "\u9810\u8A2D\u5C0D\u9F4A\u65B9\u5F0F",
  "setting.alignment.desc": "\u5716\u8868\u5728\u5BB9\u5668\u5167\u7684\u6C34\u5E73\u5C0D\u9F4A\u65B9\u5F0F\u3002",
  "setting.alignment.option.left": "\u5DE6",
  "setting.alignment.option.center": "\u7F6E\u4E2D",
  "setting.alignment.option.right": "\u53F3",
  "settings.note": "\u5916\u89C0\u8A2D\u5B9A\uFF08\u5C0D\u9F4A\u3001\u908A\u6846\uFF09\u7ACB\u5373\u5957\u7528\u65BC\u5DF2\u958B\u555F\u7684\u7B46\u8A18\uFF1B\u7E2E\u653E\u9748\u654F\u5EA6\u65BC\u5168\u87A2\u5E55\u6AA2\u8996\u4E0B\u6B21\u958B\u555F\u6642\u751F\u6548\u3002",
  "modal.close": "\u95DC\u9589",
  "modal.zoomIn": "\u653E\u5927",
  "modal.zoomOut": "\u7E2E\u5C0F",
  "modal.reset": "\u91CD\u8A2D\u7E2E\u653E"
};

// locale/ja.json
var ja_default = {
  "setting.zoomSensitivity.name": "\u30BA\u30FC\u30E0\u611F\u5EA6",
  "setting.zoomSensitivity.desc": "\u30DE\u30A6\u30B9\u30DB\u30A4\u30FC\u30EB\u3068\u30D4\u30F3\u30C1\u64CD\u4F5C\u306B\u3088\u308B\u30BA\u30FC\u30E0\u306E\u5F37\u3055\u3067\u3059\u3002\u5024\u3092\u5C0F\u3055\u304F\u3059\u308B\u3068\u3088\u308A\u7DE9\u3084\u304B\u306B\u52D5\u4F5C\u3057\u307E\u3059\u3002\u30C8\u30E9\u30C3\u30AF\u30D1\u30C3\u30C9\u3084 Magic Mouse \u3067\u30BA\u30FC\u30E0\u304C\u901F\u3059\u304E\u308B\u5834\u5408\u306F 0.5x \u3092\u8A66\u3057\u3066\u304F\u3060\u3055\u3044\u3002\u56F3\u3092\u5168\u753B\u9762\u8868\u793A\u3057\u76F4\u3059\u3068\u53CD\u6620\u3055\u308C\u307E\u3059\u3002",
  "setting.containerBorder.name": "\u30B3\u30F3\u30C6\u30CA\u306E\u67A0\u7DDA\u3092\u8868\u793A",
  "setting.containerBorder.desc": "\u5404\u56F3\u306E\u30B3\u30F3\u30C6\u30CA\u5468\u56F2\u306B\u7834\u7DDA\u306E\u67A0\u3092\u8868\u793A\u3057\u3001\u30BA\u30FC\u30E0\u9818\u57DF\u306E\u5883\u754C\u3092\u898B\u3084\u3059\u304F\u3057\u307E\u3059\u3002",
  "setting.alignment.name": "\u30C7\u30D5\u30A9\u30EB\u30C8\u306E\u914D\u7F6E",
  "setting.alignment.desc": "\u30B3\u30F3\u30C6\u30CA\u5185\u306E\u56F3\u306E\u6C34\u5E73\u65B9\u5411\u306E\u914D\u7F6E\u3067\u3059\u3002",
  "setting.alignment.option.left": "\u5DE6",
  "setting.alignment.option.center": "\u4E2D\u592E",
  "setting.alignment.option.right": "\u53F3",
  "settings.note": "\u5916\u89B3\u8A2D\u5B9A\uFF08\u914D\u7F6E\u30FB\u67A0\u7DDA\uFF09\u306F\u958B\u3044\u3066\u3044\u308B\u30CE\u30FC\u30C8\u306B\u5373\u6642\u53CD\u6620\u3055\u308C\u307E\u3059\u3002\u30BA\u30FC\u30E0\u611F\u5EA6\u306F\u56F3\u3092\u5168\u753B\u9762\u8868\u793A\u3057\u76F4\u3059\u3068\u53CD\u6620\u3055\u308C\u307E\u3059\u3002",
  "modal.close": "\u9589\u3058\u308B",
  "modal.zoomIn": "\u62E1\u5927",
  "modal.zoomOut": "\u7E2E\u5C0F",
  "modal.reset": "\u30BA\u30FC\u30E0\u3092\u30EA\u30BB\u30C3\u30C8"
};

// locale/de.json
var de_default = {
  "setting.zoomSensitivity.name": "Zoom-Empfindlichkeit",
  "setting.zoomSensitivity.desc": "Wie stark Mausrad-Scrollen und Pinch-Gesten zoomen. Niedrigere Werte f\xFChlen sich sanfter an \u2014 probieren Sie 0.5x, wenn Zoomen per Trackpad oder Magic Mouse zu schnell ist. Wird beim n\xE4chsten \xD6ffnen der Vollbildansicht wirksam.",
  "setting.containerBorder.name": "Container-Rahmen anzeigen",
  "setting.containerBorder.desc": "Zeigt einen gestrichelten Rahmen um jeden Diagramm-Container, um die Grenzen des Zoombereichs besser zu erkennen.",
  "setting.alignment.name": "Standardausrichtung",
  "setting.alignment.desc": "Horizontale Ausrichtung des Diagramms innerhalb seines Containers.",
  "setting.alignment.option.left": "Links",
  "setting.alignment.option.center": "Zentriert",
  "setting.alignment.option.right": "Rechts",
  "settings.note": "Darstellungseinstellungen (Ausrichtung, Rahmen) wirken sofort in ge\xF6ffneten Notizen; die Zoom-Empfindlichkeit wird beim n\xE4chsten \xD6ffnen der Vollbildansicht wirksam.",
  "modal.close": "Schlie\xDFen",
  "modal.zoomIn": "Vergr\xF6\xDFern",
  "modal.zoomOut": "Verkleinern",
  "modal.reset": "Zoom zur\xFCcksetzen"
};

// locale/es.json
var es_default = {
  "setting.zoomSensitivity.name": "Sensibilidad de zoom",
  "setting.zoomSensitivity.desc": "La intensidad con la que ampl\xEDan la rueda del rat\xF3n y el gesto de pellizco. Los valores bajos se sienten m\xE1s suaves: prueba 0.5x si el zoom con el trackpad o el Magic Mouse va demasiado r\xE1pido. Se aplica al volver a abrir una vista a pantalla completa.",
  "setting.containerBorder.name": "Mostrar borde del contenedor",
  "setting.containerBorder.desc": "Muestra un borde discontinuo alrededor de cada contenedor de diagrama para visualizar mejor los l\xEDmites del \xE1rea de zoom.",
  "setting.alignment.name": "Alineaci\xF3n predeterminada",
  "setting.alignment.desc": "Alineaci\xF3n horizontal del diagrama dentro de su contenedor.",
  "setting.alignment.option.left": "Izquierda",
  "setting.alignment.option.center": "Centro",
  "setting.alignment.option.right": "Derecha",
  "settings.note": "Los ajustes de apariencia (alineaci\xF3n, borde) se aplican de inmediato a las notas abiertas; la sensibilidad de zoom surte efecto al volver a abrir un diagrama a pantalla completa.",
  "modal.close": "Cerrar",
  "modal.zoomIn": "Acercar",
  "modal.zoomOut": "Alejar",
  "modal.reset": "Restablecer zoom"
};

// locale/fr.json
var fr_default = {
  "setting.zoomSensitivity.name": "Sensibilit\xE9 du zoom",
  "setting.zoomSensitivity.desc": "Intensit\xE9 du zoom \xE0 la molette de la souris et au pincement. Des valeurs plus faibles sont plus douces \u2014 essayez 0.5x si le zoom au trackpad ou \xE0 la Magic Mouse est trop rapide. Prend effet \xE0 la prochaine ouverture en plein \xE9cran.",
  "setting.containerBorder.name": "Afficher la bordure du conteneur",
  "setting.containerBorder.desc": "Affiche une bordure en pointill\xE9s autour de chaque conteneur de diagramme pour mieux visualiser les limites de la zone de zoom.",
  "setting.alignment.name": "Alignement par d\xE9faut",
  "setting.alignment.desc": "Alignement horizontal du diagramme dans son conteneur.",
  "setting.alignment.option.left": "Gauche",
  "setting.alignment.option.center": "Centre",
  "setting.alignment.option.right": "Droite",
  "settings.note": "Les r\xE9glages d'apparence (alignement, bordure) s'appliquent imm\xE9diatement aux notes ouvertes ; la sensibilit\xE9 du zoom prend effet \xE0 la prochaine ouverture en plein \xE9cran.",
  "modal.close": "Fermer",
  "modal.zoomIn": "Zoomer",
  "modal.zoomOut": "D\xE9zoomer",
  "modal.reset": "R\xE9initialiser le zoom"
};

// locale/ru.json
var ru_default = {
  "setting.zoomSensitivity.name": "\u0427\u0443\u0432\u0441\u0442\u0432\u0438\u0442\u0435\u043B\u044C\u043D\u043E\u0441\u0442\u044C \u043C\u0430\u0441\u0448\u0442\u0430\u0431\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F",
  "setting.zoomSensitivity.desc": "\u041D\u0430\u0441\u043A\u043E\u043B\u044C\u043A\u043E \u0441\u0438\u043B\u044C\u043D\u043E \u043C\u0430\u0441\u0448\u0442\u0430\u0431\u0438\u0440\u0443\u044E\u0442 \u043F\u0440\u043E\u043A\u0440\u0443\u0442\u043A\u0430 \u043A\u043E\u043B\u0435\u0441\u0430 \u043C\u044B\u0448\u0438 \u0438 \u0436\u0435\u0441\u0442 \u0449\u0438\u043F\u043A\u0430. \u041C\u0435\u043D\u044C\u0448\u0438\u0435 \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u044F \u043E\u0449\u0443\u0449\u0430\u044E\u0442\u0441\u044F \u043C\u044F\u0433\u0447\u0435 \u2014 \u043F\u043E\u043F\u0440\u043E\u0431\u0443\u0439\u0442\u0435 0.5x, \u0435\u0441\u043B\u0438 \u043C\u0430\u0441\u0448\u0442\u0430\u0431\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u043D\u0430 \u0442\u0440\u0435\u043A\u043F\u0430\u0434\u0435 \u0438\u043B\u0438 Magic Mouse \u043F\u0440\u043E\u0438\u0441\u0445\u043E\u0434\u0438\u0442 \u0441\u043B\u0438\u0448\u043A\u043E\u043C \u0431\u044B\u0441\u0442\u0440\u043E. \u041F\u0440\u0438\u043C\u0435\u043D\u044F\u0435\u0442\u0441\u044F \u043F\u0440\u0438 \u0441\u043B\u0435\u0434\u0443\u044E\u0449\u0435\u043C \u043E\u0442\u043A\u0440\u044B\u0442\u0438\u0438 \u043F\u043E\u043B\u043D\u043E\u044D\u043A\u0440\u0430\u043D\u043D\u043E\u0433\u043E \u043F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\u0430.",
  "setting.containerBorder.name": "\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0440\u0430\u043C\u043A\u0443 \u043A\u043E\u043D\u0442\u0435\u0439\u043D\u0435\u0440\u0430",
  "setting.containerBorder.desc": "\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0435\u0442 \u043F\u0443\u043D\u043A\u0442\u0438\u0440\u043D\u0443\u044E \u0440\u0430\u043C\u043A\u0443 \u0432\u043E\u043A\u0440\u0443\u0433 \u043A\u0430\u0436\u0434\u043E\u0433\u043E \u043A\u043E\u043D\u0442\u0435\u0439\u043D\u0435\u0440\u0430 \u0434\u0438\u0430\u0433\u0440\u0430\u043C\u043C\u044B, \u0447\u0442\u043E\u0431\u044B \u043B\u0443\u0447\u0448\u0435 \u0432\u0438\u0434\u0435\u0442\u044C \u0433\u0440\u0430\u043D\u0438\u0446\u044B \u043E\u0431\u043B\u0430\u0441\u0442\u0438 \u043C\u0430\u0441\u0448\u0442\u0430\u0431\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F.",
  "setting.alignment.name": "\u0412\u044B\u0440\u0430\u0432\u043D\u0438\u0432\u0430\u043D\u0438\u0435 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
  "setting.alignment.desc": "\u0413\u043E\u0440\u0438\u0437\u043E\u043D\u0442\u0430\u043B\u044C\u043D\u043E\u0435 \u0432\u044B\u0440\u0430\u0432\u043D\u0438\u0432\u0430\u043D\u0438\u0435 \u0434\u0438\u0430\u0433\u0440\u0430\u043C\u043C\u044B \u0432\u043D\u0443\u0442\u0440\u0438 \u043A\u043E\u043D\u0442\u0435\u0439\u043D\u0435\u0440\u0430.",
  "setting.alignment.option.left": "\u0421\u043B\u0435\u0432\u0430",
  "setting.alignment.option.center": "\u041F\u043E \u0446\u0435\u043D\u0442\u0440\u0443",
  "setting.alignment.option.right": "\u0421\u043F\u0440\u0430\u0432\u0430",
  "settings.note": "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0432\u043D\u0435\u0448\u043D\u0435\u0433\u043E \u0432\u0438\u0434\u0430 (\u0432\u044B\u0440\u0430\u0432\u043D\u0438\u0432\u0430\u043D\u0438\u0435, \u0440\u0430\u043C\u043A\u0430) \u043D\u0435\u043C\u0435\u0434\u043B\u0435\u043D\u043D\u043E \u043F\u0440\u0438\u043C\u0435\u043D\u044F\u044E\u0442\u0441\u044F \u043A \u043E\u0442\u043A\u0440\u044B\u0442\u044B\u043C \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C; \u0447\u0443\u0432\u0441\u0442\u0432\u0438\u0442\u0435\u043B\u044C\u043D\u043E\u0441\u0442\u044C \u043C\u0430\u0441\u0448\u0442\u0430\u0431\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F \u0434\u0435\u0439\u0441\u0442\u0432\u0443\u0435\u0442 \u043F\u0440\u0438 \u0441\u043B\u0435\u0434\u0443\u044E\u0449\u0435\u043C \u043E\u0442\u043A\u0440\u044B\u0442\u0438\u0438 \u043F\u043E\u043B\u043D\u043E\u044D\u043A\u0440\u0430\u043D\u043D\u043E\u0433\u043E \u043F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\u0430.",
  "modal.close": "\u0417\u0430\u043A\u0440\u044B\u0442\u044C",
  "modal.zoomIn": "\u0423\u0432\u0435\u043B\u0438\u0447\u0438\u0442\u044C",
  "modal.zoomOut": "\u0423\u043C\u0435\u043D\u044C\u0448\u0438\u0442\u044C",
  "modal.reset": "\u0421\u0431\u0440\u043E\u0441\u0438\u0442\u044C \u043C\u0430\u0441\u0448\u0442\u0430\u0431"
};

// locale/pt-BR.json
var pt_BR_default = {
  "setting.zoomSensitivity.name": "Sensibilidade do zoom",
  "setting.zoomSensitivity.desc": "Qu\xE3o forte o zoom responde \xE0 roda do mouse e ao gesto de pin\xE7a. Valores menores s\xE3o mais suaves \u2014 tente 0.5x se o zoom no trackpad ou Magic Mouse for r\xE1pido demais. Surte efeito ao reabrir a visualiza\xE7\xE3o em tela cheia.",
  "setting.containerBorder.name": "Mostrar borda do cont\xEAiner",
  "setting.containerBorder.desc": "Exibe uma borda tracejada ao redor de cada cont\xEAiner de diagrama para ajudar a visualizar os limites da \xE1rea de zoom.",
  "setting.alignment.name": "Alinhamento padr\xE3o",
  "setting.alignment.desc": "Alinhamento horizontal do diagrama dentro de seu cont\xEAiner.",
  "setting.alignment.option.left": "Esquerda",
  "setting.alignment.option.center": "Centro",
  "setting.alignment.option.right": "Direita",
  "settings.note": "As configura\xE7\xF5es de apar\xEAncia (alinhamento, borda) se aplicam imediatamente \xE0s notas abertas; a sensibilidade do zoom surte efeito ao reabrir a visualiza\xE7\xE3o em tela cheia.",
  "modal.close": "Fechar",
  "modal.zoomIn": "Ampliar",
  "modal.zoomOut": "Reduzir",
  "modal.reset": "Redefinir zoom"
};

// locale/ko.json
var ko_default = {
  "setting.zoomSensitivity.name": "\uD655\uB300/\uCD95\uC18C \uBBFC\uAC10\uB3C4",
  "setting.zoomSensitivity.desc": "\uB9C8\uC6B0\uC2A4 \uD720\uACFC \uC9D1\uAE30 \uC81C\uC2A4\uCC98\uC758 \uD655\uB300/\uCD95\uC18C \uAC15\uB3C4\uC785\uB2C8\uB2E4. \uAC12\uC774 \uB0AE\uC744\uC218\uB85D \uBD80\uB4DC\uB7FD\uAC8C \uC791\uB3D9\uD558\uBA70, \uD2B8\uB799\uD328\uB4DC\uB098 \uB9E4\uC9C1 \uB9C8\uC6B0\uC2A4\uC5D0\uC11C \uD655\uB300/\uCD95\uC18C\uAC00 \uB108\uBB34 \uBE60\uB974\uBA74 0.5x\uB97C \uC0AC\uC6A9\uD574 \uBCF4\uC138\uC694. \uC804\uCCB4 \uD654\uBA74 \uBCF4\uAE30\uB97C \uB2E4\uC2DC \uC5F4\uBA74 \uC801\uC6A9\uB429\uB2C8\uB2E4.",
  "setting.containerBorder.name": "\uCEE8\uD14C\uC774\uB108 \uD14C\uB450\uB9AC \uD45C\uC2DC",
  "setting.containerBorder.desc": "\uAC01 \uB2E4\uC774\uC5B4\uADF8\uB7A8 \uCEE8\uD14C\uC774\uB108 \uC8FC\uC704\uC5D0 \uC810\uC120 \uD14C\uB450\uB9AC\uB97C \uD45C\uC2DC\uD558\uC5EC \uD655\uB300/\uCD95\uC18C \uC601\uC5ED\uC758 \uACBD\uACC4\uB97C \uC27D\uAC8C \uD655\uC778\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
  "setting.alignment.name": "\uAE30\uBCF8 \uC815\uB82C",
  "setting.alignment.desc": "\uCEE8\uD14C\uC774\uB108 \uB0B4 \uB2E4\uC774\uC5B4\uADF8\uB7A8\uC758 \uAC00\uB85C \uC815\uB82C\uC785\uB2C8\uB2E4.",
  "setting.alignment.option.left": "\uC67C\uCABD",
  "setting.alignment.option.center": "\uAC00\uC6B4\uB370",
  "setting.alignment.option.right": "\uC624\uB978\uCABD",
  "settings.note": "\uC678\uD615 \uC124\uC815(\uC815\uB82C, \uD14C\uB450\uB9AC)\uC740 \uC5F4\uB9B0 \uB178\uD2B8\uC5D0 \uC989\uC2DC \uC801\uC6A9\uB429\uB2C8\uB2E4. \uD655\uB300/\uCD95\uC18C \uBBFC\uAC10\uB3C4\uB294 \uC804\uCCB4 \uD654\uBA74 \uBCF4\uAE30\uB97C \uB2E4\uC2DC \uC5F4\uBA74 \uC801\uC6A9\uB429\uB2C8\uB2E4.",
  "modal.close": "\uB2EB\uAE30",
  "modal.zoomIn": "\uD655\uB300",
  "modal.zoomOut": "\uCD95\uC18C",
  "modal.reset": "\uD655\uB300/\uCD95\uC18C \uC7AC\uC124\uC815"
};

// i18n.ts
var translations = {
  en: en_default,
  zh: zh_default,
  "zh-TW": zh_TW_default,
  ja: ja_default,
  de: de_default,
  es: es_default,
  fr: fr_default,
  ru: ru_default,
  "pt-BR": pt_BR_default,
  pt: pt_BR_default,
  // European Portuguese falls back to the Brazilian translation.
  ko: ko_default
};
function resolveDict(lang) {
  var _a;
  if (translations[lang])
    return translations[lang];
  const base = lang.split("-")[0];
  return (_a = translations[base]) != null ? _a : translations.en;
}
var dict = resolveDict((0, import_obsidian.getLanguage)());
function t(key) {
  var _a, _b;
  return (_b = (_a = dict[key]) != null ? _a : translations.en[key]) != null ? _b : key;
}

// settings.ts
var DEFAULT_SETTINGS = {
  zoomSensitivity: 1,
  showContainerBorder: false,
  alignment: "center",
  exportDestination: "vault"
};
var MermaidZoomSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  // Declarative settings API (Obsidian 1.13.0+). When this returns a
  // non-empty array, Obsidian renders the tab from these definitions and
  // indexes them for settings search; display() is used as the fallback for
  // older Obsidian versions.
  getSettingDefinitions() {
    return [
      {
        name: t("setting.zoomSensitivity.name"),
        desc: t("setting.zoomSensitivity.desc"),
        control: {
          type: "slider",
          key: "zoomSensitivity",
          min: 0.2,
          max: 3,
          step: 0.1,
          defaultValue: 1,
          displayFormat: (value) => `${value}x`
        }
      },
      {
        name: t("setting.containerBorder.name"),
        desc: t("setting.containerBorder.desc"),
        control: {
          type: "toggle",
          key: "showContainerBorder",
          defaultValue: false
        }
      },
      {
        name: t("setting.alignment.name"),
        desc: t("setting.alignment.desc"),
        control: {
          type: "dropdown",
          key: "alignment",
          options: {
            left: t("setting.alignment.option.left"),
            center: t("setting.alignment.option.center"),
            right: t("setting.alignment.option.right")
          },
          defaultValue: "center"
        }
      },
      {
        name: t("setting.exportDestination.name"),
        desc: t("setting.exportDestination.desc"),
        control: {
          type: "dropdown",
          key: "exportDestination",
          options: {
            vault: t("setting.exportDestination.option.vault"),
            download: t("setting.exportDestination.option.download")
          },
          defaultValue: "vault"
        }
      }
    ];
  }
  // Persist declarative-control writes through the plugin's own saver so
  // data.json stays in sync. (The base reads from this.plugin.settings.)
  async setControlValue(key, value) {
    this.plugin.settings[key] = value;
    await this.plugin.saveSettings();
    if (key === "alignment" || key === "showContainerBorder") {
      this.plugin.decorateAllMermaidBlocks();
    }
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName(t("setting.zoomSensitivity.name")).setDesc(t("setting.zoomSensitivity.desc")).addSlider((slider) => slider.setLimits(0.2, 3, 0.1).setValue(this.plugin.settings.zoomSensitivity).onChange(async (value) => {
      this.plugin.settings.zoomSensitivity = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(t("setting.containerBorder.name")).setDesc(t("setting.containerBorder.desc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showContainerBorder).onChange(async (value) => {
      this.plugin.settings.showContainerBorder = value;
      await this.plugin.saveSettings();
      this.plugin.decorateAllMermaidBlocks();
    }));
    new import_obsidian2.Setting(containerEl).setName(t("setting.alignment.name")).setDesc(t("setting.alignment.desc")).addDropdown((dropdown) => dropdown.addOption("left", t("setting.alignment.option.left")).addOption("center", t("setting.alignment.option.center")).addOption("right", t("setting.alignment.option.right")).setValue(this.plugin.settings.alignment).onChange(async (value) => {
      this.plugin.settings.alignment = value;
      await this.plugin.saveSettings();
      this.plugin.decorateAllMermaidBlocks();
    }));
    new import_obsidian2.Setting(containerEl).setName(t("setting.exportDestination.name")).setDesc(t("setting.exportDestination.desc")).addDropdown((dropdown) => dropdown.addOption("vault", t("setting.exportDestination.option.vault")).addOption("download", t("setting.exportDestination.option.download")).setValue(this.plugin.settings.exportDestination).onChange(async (value) => {
      this.plugin.settings.exportDestination = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("p", {
      text: t("settings.note"),
      cls: "setting-item-description"
    });
  }
};

// gestures.ts
function updateTransform(contentWrapper, state) {
  contentWrapper.style.transform = `translate(${state.translateX}px, ${state.translateY}px) scale(${state.scale})`;
  if (state.scaleIndicator) {
    state.scaleIndicator.textContent = `${Math.round(state.scale * 100)}%`;
  }
}
function zoom(contentWrapper, state, factor) {
  let newScale = state.scale * factor;
  newScale = Math.max(state.minScale, Math.min(state.maxScale, newScale));
  const container = state.container;
  const rect = container.getBoundingClientRect();
  const centerX = rect.width / 2;
  const centerY = rect.height / 2;
  const scaleRatio = newScale / state.scale;
  state.translateX = centerX - (centerX - state.translateX) * scaleRatio;
  state.translateY = centerY - (centerY - state.translateY) * scaleRatio;
  state.scale = newScale;
  updateTransform(contentWrapper, state);
}
function addWheelZoom(container, contentWrapper, state, sensitivity = 1) {
  const wheelHandler = (e) => {
    e.preventDefault();
    const rect = container.getBoundingClientRect();
    const mouseX = e.clientX - rect.left;
    const mouseY = e.clientY - rect.top;
    let deltaPx = e.deltaY;
    if (e.deltaMode === 1)
      deltaPx *= 33;
    else if (e.deltaMode === 2)
      deltaPx *= 300;
    const clamped = Math.max(-100, Math.min(100, deltaPx));
    const factor = Math.exp(-clamped / 100 * 0.12 * sensitivity);
    const oldScale = state.scale;
    let newScale = oldScale * factor;
    newScale = Math.max(state.minScale, Math.min(state.maxScale, newScale));
    if (newScale !== oldScale) {
      const scaleRatio = newScale / oldScale;
      state.translateX = mouseX - (mouseX - state.translateX) * scaleRatio;
      state.translateY = mouseY - (mouseY - state.translateY) * scaleRatio;
      state.scale = newScale;
      updateTransform(contentWrapper, state);
    }
  };
  container.addEventListener("wheel", wheelHandler, { passive: false });
  return () => container.removeEventListener("wheel", wheelHandler);
}
function addDragPan(container, contentWrapper, state) {
  container.addEventListener("mousedown", (e) => {
    if (e.button === 0) {
      state.isDragging = true;
      state.startX = e.clientX - state.translateX;
      state.startY = e.clientY - state.translateY;
      contentWrapper.addClass("dragging");
    }
  });
  const onMouseMove = (e) => {
    if (state.isDragging) {
      e.preventDefault();
      state.translateX = e.clientX - state.startX;
      state.translateY = e.clientY - state.startY;
      updateTransform(contentWrapper, state);
    }
  };
  const onMouseUp = () => {
    if (state.isDragging) {
      state.isDragging = false;
      contentWrapper.removeClass("dragging");
    }
  };
  document.addEventListener("mousemove", onMouseMove);
  document.addEventListener("mouseup", onMouseUp);
  return () => {
    document.removeEventListener("mousemove", onMouseMove);
    document.removeEventListener("mouseup", onMouseUp);
  };
}
function addTouchGestures(container, contentWrapper, state, sensitivity = 1) {
  let initialDistance = 0;
  let initialScale = 1;
  let initialTranslateX = 0;
  let initialTranslateY = 0;
  let initialCenterX = 0;
  let initialCenterY = 0;
  const onTouchStart = (e) => {
    if (e.touches.length === 2) {
      const touch1 = e.touches[0];
      const touch2 = e.touches[1];
      initialDistance = Math.hypot(
        touch2.clientX - touch1.clientX,
        touch2.clientY - touch1.clientY
      );
      initialScale = state.scale;
      initialTranslateX = state.translateX;
      initialTranslateY = state.translateY;
      const rect = container.getBoundingClientRect();
      initialCenterX = (touch1.clientX + touch2.clientX) / 2 - rect.left;
      initialCenterY = (touch1.clientY + touch2.clientY) / 2 - rect.top;
      state.isDragging = false;
    } else if (e.touches.length === 1) {
      state.isDragging = true;
      state.startX = e.touches[0].clientX - state.translateX;
      state.startY = e.touches[0].clientY - state.translateY;
    }
  };
  const onTouchMove = (e) => {
    e.preventDefault();
    if (e.touches.length === 2) {
      if (initialDistance === 0)
        return;
      const touch1 = e.touches[0];
      const touch2 = e.touches[1];
      const currentDistance = Math.hypot(
        touch2.clientX - touch1.clientX,
        touch2.clientY - touch1.clientY
      );
      const scaleRatio = currentDistance / initialDistance;
      let newScale = initialScale * Math.pow(scaleRatio, sensitivity);
      newScale = Math.max(state.minScale, Math.min(state.maxScale, newScale));
      const rect = container.getBoundingClientRect();
      const currentCenterX = (touch1.clientX + touch2.clientX) / 2 - rect.left;
      const currentCenterY = (touch1.clientY + touch2.clientY) / 2 - rect.top;
      const appliedScaleRatio = newScale / initialScale;
      state.translateX = currentCenterX - (initialCenterX - initialTranslateX) * appliedScaleRatio;
      state.translateY = currentCenterY - (initialCenterY - initialTranslateY) * appliedScaleRatio;
      state.scale = newScale;
      updateTransform(contentWrapper, state);
    } else if (e.touches.length === 1 && state.isDragging) {
      state.translateX = e.touches[0].clientX - state.startX;
      state.translateY = e.touches[0].clientY - state.startY;
      updateTransform(contentWrapper, state);
    }
  };
  const onTouchEnd = () => {
    state.isDragging = false;
  };
  container.addEventListener("touchstart", onTouchStart);
  container.addEventListener("touchmove", onTouchMove, { passive: false });
  container.addEventListener("touchend", onTouchEnd);
  container.addEventListener("touchcancel", onTouchEnd);
  return () => {
    container.removeEventListener("touchstart", onTouchStart);
    container.removeEventListener("touchmove", onTouchMove);
    container.removeEventListener("touchend", onTouchEnd);
    container.removeEventListener("touchcancel", onTouchEnd);
  };
}

// export.ts
var import_obsidian3 = require("obsidian");
async function svgToPngBlob(svg, width, height, scale = 2) {
  const clone = svg.cloneNode(true);
  clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
  clone.setAttribute("width", String(width));
  clone.setAttribute("height", String(height));
  clone.style.removeProperty("transform");
  const svgDataUrl = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(new XMLSerializer().serializeToString(clone));
  const img = new Image();
  const loaded = new Promise((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error("SVG image failed to load"));
  });
  img.src = svgDataUrl;
  await loaded;
  const canvas = createEl("canvas");
  canvas.width = Math.max(1, Math.round(width * scale));
  canvas.height = Math.max(1, Math.round(height * scale));
  const ctx = canvas.getContext("2d");
  if (!ctx)
    throw new Error("Canvas 2D context unavailable");
  ctx.scale(scale, scale);
  ctx.drawImage(img, 0, 0, width, height);
  const blob = await new Promise((resolve) => canvas.toBlob(resolve, "image/png"));
  if (!blob)
    throw new Error("Canvas failed to produce a PNG");
  return blob;
}
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = createEl("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
async function exportDiagramPng(app, svg, width, height, destination) {
  var _a;
  try {
    const blob = await svgToPngBlob(svg, width, height, 2);
    const active = app.workspace.getActiveFile();
    const filename = ((_a = active == null ? void 0 : active.basename) != null ? _a : "diagram") + ".png";
    if (destination === "download") {
      downloadBlob(blob, filename);
      new import_obsidian3.Notice(t("export.downloadedNotice").replace("{name}", filename));
    } else {
      const path = await app.fileManager.getAvailablePathForAttachment(filename, active == null ? void 0 : active.path);
      await app.vault.createBinary(path, await blob.arrayBuffer());
      new import_obsidian3.Notice(t("export.savedNotice").replace("{path}", path));
    }
  } catch (err) {
    console.error("Mermaid Zoom: PNG export failed", err);
    new import_obsidian3.Notice(t("export.failedNotice"));
  }
}

// main.ts
var MermaidZoomPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.defaultMinScale = 0.1;
    this.defaultMaxScale = 5;
    this.settings = DEFAULT_SETTINGS;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MermaidZoomSettingTab(this.app, this));
    console.debug("Loading Mermaid Zoom plugin");
    this.setupMutationObserver();
    this.app.workspace.onLayoutReady(() => {
      this.decorateAllMermaidBlocks();
    });
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      this.decorateAllMermaidBlocks();
    }));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => {
      this.decorateAllMermaidBlocks();
    }));
    this.registerEvent(this.app.workspace.on("file-open", () => {
      window.setTimeout(() => this.decorateAllMermaidBlocks(), 200);
    }));
  }
  setupMutationObserver() {
    this.mutationObserver = new MutationObserver((mutations) => {
      for (const mutation of Array.from(mutations)) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (node.instanceOf(HTMLElement)) {
            this.decorateMermaidBlocksIn(node);
          }
        }
      }
    });
    this.mutationObserver.observe(document.body, {
      childList: true,
      subtree: true
    });
  }
  // Obsidian structure: <div class="mermaid"><svg id="mermaid-xxx">...</svg></div>.
  // A bare .mermaid div may be added before its svg renders, and a rendered
  // svg may be injected into an existing div — catch both shapes.
  decorateMermaidBlocksIn(root) {
    const blocks = Array.from(root.querySelectorAll(".mermaid"));
    if (root.classList.contains("mermaid")) {
      blocks.push(root);
    } else {
      for (const svg of Array.from(root.querySelectorAll(".mermaid svg"))) {
        const host = svg.closest(".mermaid");
        if (host)
          blocks.push(host);
      }
    }
    for (const block of blocks) {
      this.decorateMermaidBlock(block);
    }
  }
  /** Decorate every mermaid block in the document; also re-syncs appearance
   * classes (used after settings change). */
  decorateAllMermaidBlocks() {
    const blocks = document.querySelectorAll(".mermaid");
    for (const block of Array.from(blocks)) {
      this.decorateMermaidBlock(block);
    }
  }
  // Appearance classes are re-applied on every visit — the operation is
  // idempotent, and it keeps re-attached blocks in sync: live preview
  // detaches far embeds and re-attaches the SAME cached node when you
  // scroll back, so a node that missed a settings change must catch up the
  // moment it reappears. The mermaid-zoom-ready marker only guards the
  // one-time button insert.
  decorateMermaidBlock(block) {
    if (!block.querySelector("svg"))
      return;
    block.removeClass("mermaid-zoom-align-left", "mermaid-zoom-align-center", "mermaid-zoom-align-right");
    block.addClass(`mermaid-zoom-align-${this.settings.alignment}`);
    block.toggleClass("mermaid-zoom-bordered", this.settings.showContainerBorder);
    if (!block.hasClass("mermaid-zoom-ready")) {
      block.addClass("mermaid-zoom-ready");
      this.addFullscreenButton(block);
    }
  }
  addFullscreenButton(block) {
    const fullscreenBtn = block.createEl("button", {
      cls: "mermaid-zoom-icon-btn mermaid-zoom-fullscreen-btn"
    });
    const svgNS = "http://www.w3.org/2000/svg";
    const svg = document.createElementNS(svgNS, "svg");
    svg.setAttribute("width", "18");
    svg.setAttribute("height", "18");
    svg.setAttribute("viewBox", "0 0 16 16");
    svg.setAttribute("fill", "none");
    svg.setAttribute("stroke", "currentColor");
    svg.setAttribute("stroke-width", "1");
    svg.setAttribute("stroke-linecap", "round");
    svg.setAttribute("stroke-linejoin", "round");
    const polyline1 = document.createElementNS(svgNS, "polyline");
    polyline1.setAttribute("points", "1,10 1,15 6,15");
    svg.appendChild(polyline1);
    const polyline2 = document.createElementNS(svgNS, "polyline");
    polyline2.setAttribute("points", "15,10 15,15 10,15");
    svg.appendChild(polyline2);
    const polyline3 = document.createElementNS(svgNS, "polyline");
    polyline3.setAttribute("points", "1,6 1,1 6,1");
    svg.appendChild(polyline3);
    const polyline4 = document.createElementNS(svgNS, "polyline");
    polyline4.setAttribute("points", "15,6 15,1 10,1");
    svg.appendChild(polyline4);
    fullscreenBtn.appendChild(svg);
    fullscreenBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const currentSvg = block.querySelector("svg");
      if (currentSvg) {
        this.openFullscreenModal(currentSvg);
      }
    });
  }
  openFullscreenModal(sourceSvg) {
    var _a;
    const controlsRight = import_obsidian4.Platform.isMobile ? "20px" : "15px";
    const controlsBottom = import_obsidian4.Platform.isMobile ? "28px" : "15px";
    const modal = createDiv();
    modal.className = "mermaid-zoom-modal";
    modal.style.cssText = `
			position: fixed;
			inset: 0;
			background: var(--background-primary);
			z-index: 9999;
			display: flex;
			flex-direction: column;
			box-sizing: border-box;
		`;
    const content = createDiv();
    content.className = "mermaid-zoom-modal-content";
    content.style.cssText = `
			flex: 1;
			overflow: hidden;
			position: relative;
			display: flex;
			align-items: center;
			justify-content: center;
		`;
    const modalZoomContainer = createDiv();
    modalZoomContainer.className = "mermaid-zoom-modal-zoom-container";
    modalZoomContainer.style.cssText = `
			width: 100%;
			height: 100%;
			overflow: hidden;
			position: relative;
		`;
    const modalContentWrapper = createDiv();
    modalContentWrapper.className = "mermaid-zoom-modal-wrapper";
    modalContentWrapper.style.cssText = `
			transform-origin: 0 0;
			transition: transform 0.1s ease-out;
			width: fit-content;
			position: absolute;
		`;
    const svgClone = sourceSvg.cloneNode(true);
    modalContentWrapper.appendChild(svgClone);
    modalZoomContainer.appendChild(modalContentWrapper);
    content.appendChild(modalZoomContainer);
    const cloneRect = svgClone.getBoundingClientRect();
    const viewBox = (_a = svgClone.viewBox) == null ? void 0 : _a.baseVal;
    const svgOriginalWidth = cloneRect.width || (viewBox == null ? void 0 : viewBox.width) || parseFloat(svgClone.getAttribute("width") || "") || 300;
    const svgOriginalHeight = cloneRect.height || (viewBox == null ? void 0 : viewBox.height) || parseFloat(svgClone.getAttribute("height") || "") || 200;
    const modalState = {
      scale: 1,
      minScale: this.defaultMinScale,
      maxScale: this.defaultMaxScale,
      isDragging: false,
      startX: 0,
      startY: 0,
      translateX: 0,
      translateY: 0,
      svg: svgClone,
      container: modalZoomContainer,
      svgOriginalWidth,
      svgOriginalHeight
    };
    const controls = createDiv();
    controls.className = "mermaid-zoom-modal-controls";
    controls.style.cssText = `
			position: absolute;
			bottom: ${controlsBottom};
			right: ${controlsRight};
			z-index: 1;
			display: flex;
			align-items: center;
			gap: 2px;
		`;
    const makeIconButton = (iconId, label, onClick) => {
      const btn = createEl("button", { cls: "mermaid-zoom-icon-btn" });
      (0, import_obsidian4.setIcon)(btn, iconId);
      btn.setAttribute("aria-label", label);
      btn.title = label;
      btn.addEventListener("click", (e) => {
        e.stopPropagation();
        onClick();
      });
      controls.appendChild(btn);
    };
    makeIconButton("plus", t("modal.zoomIn"), () => zoom(modalContentWrapper, modalState, 1.2));
    makeIconButton("minus", t("modal.zoomOut"), () => zoom(modalContentWrapper, modalState, 0.8));
    makeIconButton("rotate-ccw", t("modal.reset"), () => {
      this.fitToContainerModal(modalZoomContainer, modalContentWrapper, modalState);
    });
    const scaleIndicator = createSpan({ cls: "mermaid-zoom-scale" });
    scaleIndicator.style.cssText = `
			min-width: 38px;
			text-align: center;
			font-size: 12px;
			font-family: var(--font-ui-medium);
			color: var(--text-muted);
		`;
    modalState.scaleIndicator = scaleIndicator;
    controls.appendChild(scaleIndicator);
    makeIconButton("download", t("export.buttonTitle"), () => {
      void exportDiagramPng(this.app, svgClone, svgOriginalWidth, svgOriginalHeight, this.settings.exportDestination);
    });
    const closeBtn = createEl("button", { cls: "mermaid-zoom-icon-btn mermaid-zoom-modal-close" });
    (0, import_obsidian4.setIcon)(closeBtn, "x");
    closeBtn.setAttribute("aria-label", t("modal.close"));
    closeBtn.title = t("modal.close");
    controls.appendChild(closeBtn);
    modal.appendChild(controls);
    modal.appendChild(content);
    const modalCleanupFns = [];
    modalCleanupFns.push(addWheelZoom(modalZoomContainer, modalContentWrapper, modalState, this.settings.zoomSensitivity));
    modalCleanupFns.push(addDragPan(modalZoomContainer, modalContentWrapper, modalState));
    modalCleanupFns.push(addTouchGestures(modalZoomContainer, modalContentWrapper, modalState, this.settings.zoomSensitivity));
    const popstateHandler = () => closeModal();
    const closeModal = () => {
      window.removeEventListener("popstate", popstateHandler);
      for (const cleanup of modalCleanupFns) {
        cleanup();
      }
      modal.remove();
      document.removeEventListener("keydown", handleKeydown);
    };
    const handleKeydown = (e) => {
      if (e.key === "Escape") {
        closeModal();
      } else if (e.key === "+" || e.key === "=") {
        zoom(modalContentWrapper, modalState, 1.2);
      } else if (e.key === "-" || e.key === "_") {
        zoom(modalContentWrapper, modalState, 0.8);
      } else if (e.key === "0") {
        this.fitToContainerModal(modalZoomContainer, modalContentWrapper, modalState);
      }
    };
    document.addEventListener("keydown", handleKeydown);
    if (import_obsidian4.Platform.isMobile) {
      history.pushState(null, "");
      window.addEventListener("popstate", popstateHandler);
    }
    closeBtn.addEventListener("click", closeModal);
    document.body.appendChild(modal);
    window.requestAnimationFrame(() => {
      this.fitToContainerModal(modalZoomContainer, modalContentWrapper, modalState);
    });
  }
  fitToContainerModal(container, contentWrapper, state) {
    if (container.clientWidth <= 0 || container.clientHeight <= 0)
      return;
    if (state.svgOriginalWidth <= 0 || state.svgOriginalHeight <= 0)
      return;
    const padding = 40;
    const availableWidth = container.clientWidth - padding * 2;
    const availableHeight = container.clientHeight - padding * 2;
    const svgWidth = state.svgOriginalWidth;
    const svgHeight = state.svgOriginalHeight;
    const scaleX = availableWidth / svgWidth;
    const scaleY = availableHeight / svgHeight;
    const fitScale = Math.min(scaleX, scaleY, 2);
    const scaledWidth = svgWidth * fitScale;
    const scaledHeight = svgHeight * fitScale;
    const centerX = (container.clientWidth - scaledWidth) / 2;
    const centerY = (container.clientHeight - scaledHeight) / 2;
    state.scale = fitScale;
    state.translateX = centerX;
    state.translateY = centerY;
    updateTransform(contentWrapper, state);
  }
  onunload() {
    var _a;
    console.debug("Unloading Mermaid Zoom plugin");
    (_a = this.mutationObserver) == null ? void 0 : _a.disconnect();
    const decorated = document.querySelectorAll(".mermaid-zoom-ready");
    for (const block of Array.from(decorated)) {
      block.removeClass(
        "mermaid-zoom-ready",
        "mermaid-zoom-bordered",
        "mermaid-zoom-align-left",
        "mermaid-zoom-align-center",
        "mermaid-zoom-align-right"
      );
      for (const btn of Array.from(block.querySelectorAll(".mermaid-zoom-fullscreen-btn"))) {
        btn.remove();
      }
    }
  }
};

/* nosourcemap */